---
# Project info
site_name: PnP Modern Search - Core Components
repo_name: PnP Modern Search - Core Components
repo_url: ""
use_directory_urls: true

# Navigation
nav:
  - Home: index.md
  - Development guide:
      - Getting started: development/getting_started.md
      - Concepts:
        - Deployment: development/concepts/deployment.md
        - Technologies used: development/concepts/solution.md
        - Localization: development/concepts/localization.md

# Configuration
theme:
  name: material
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: ""
      
extra_css:
  - 'assets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include:
          base_path: docs

extra_javascript:
  - fix-trailing-slash.js

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: date
